export const GET_WEATHER = 'GET_WEATHER';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_ICON = 'SET_ICON';
export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING';
export const TOGGLE_IS_WEATHER_UPDATING = 'TOGGLE_IS_WEATHER_UPDATING';
export const SET_ERROR = 'SET_ERROR';